# Generated by Django 3.2.6 on 2021-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curationmodel",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
