# Generated by Django 4.0.2 on 2022-02-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curations', '0002_alter_curation_owner'),
        ('curations', '0002_alter_curation_subject'),
    ]

    operations = [
    ]
