# Generated by Django 3.2.6 on 2021-09-09 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curations', '0003_auto_20210909_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurationModel',
            new_name='Curation',
        ),
        migrations.RenameModel(
            old_name='LinkModel',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='SubjectModel',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='SubTopicModel',
            new_name='SubTopic',
        ),
        migrations.RenameModel(
            old_name='SubTopicLinkModel',
            new_name='SubTopicLink',
        ),
        migrations.RenameModel(
            old_name='TopicModel',
            new_name='Topic',
        ),
    ]
